### ISSUE TITLE
error operands could not be broadcast together with shapes at img - np.real

### ISSUE THREAD

**Issue by kovalepskaia** [imoken1122/GIST-feature-extractor#3]
![image](https://github.com/imoken1122/GIST-feature-extractor/assets/13298750/86a36458-6718-43bf-9fd7-bb807375aeac)

**Comment by imoken1122** [comment]
Hello, thank you for reporting the problem.
Please try entering an image with width>=heigth, as it will not run correctly if width<height.

**Comment by kovalepskaia** [comment]
run error some images with size 139x114, 957x771, 657x849. So that, I don't think size it is the problem, but I think padding and meshgrid are not correct

**Comment by imoken1122** [comment]
Thanks for the error report.
I fixed that bug , added support for various image scales.

I made some modifications to this [gist.py:74] .
```
if sn == sm:
        img = np.pad(img,[0,int(n-sn)],"symmetric")
elif sn <= sm:
    img = np.pad(img,[0,int(n-sn)], "symmetric")[:,:sm]
else:
    img = np.pad(img, [0, int(n - sm)], "symmetric")[sn - sm:]
```

**Comment by kovalepskaia** [comment]
Some images I run successfully, but the image's size 139x114 is error 
![image](https://github.com/imoken1122/GIST-feature-extractor/assets/13298750/911b9ca0-29bc-4009-911f-c81afde716ea)

**Comment by kovalepskaia** [comment]
You can check some images
![fake_adidas_15](https://github.com/imoken1122/GIST-feature-extractor/assets/13298750/5b9bd5e8-9ae2-4661-b9cb-2d8ebf55b09f)
![fake_adidas_20](https://github.com/imoken1122/GIST-feature-extractor/assets/13298750/d0647531-865e-47aa-87d8-a62bbba865c5)

**Comment by imoken1122** [comment]
Perhaps this bug could be fixed completely, please clone and try.

**Comment by kovalepskaia** [comment]
Code has run successfully. But I have a small issue: the condition for padding:
             sn == sm and sn <= sm overlap each other.
